apiVersion: v1
kind: Service
metadata:
  name: health-monitor-service
spec:
  type: NodePort
  selector:
    app: health-monitor
  ports:
    - port: 80          # Service port inside the cluster
      targetPort: 5000  # Container port
      nodePort: 30080   # Port on your machine (must be 30000â€“32767)
